parameters:
    application.arguments: []

services:
    _defaults:
        autowire: true
        public: false

    _instanceof:
        ArticlesApp\Command\AbstractCommand:
            tags: ['application.command']
        ArticlesApp\Service\ExternalApi\AbstractExternalApiClientService:
            tags: ['application.external_api_client']

    ArticlesApp\:
        resource: '../src/*'
        exclude: '../src/{Application/ApplicationContainer.php,console.php}'

    ArticlesApp\Application\CommandLineApplication:
        arguments:
            $arguments: '%application.arguments%'
        public: true

    ArticlesApp\Command\CommandFactory:
        arguments:
            - !tagged_iterator application.command

    ArticlesApp\Service\ExternalApi\ExternalApiClientServiceFactory:
        arguments:
            - !tagged_iterator application.external_api_client

    Symfony\Component\Filesystem\Filesystem: ~

    Psr\Http\Client\ClientInterface:
        class: Symfony\Component\HttpClient\Psr18Client
